portable.h: fix build with gcc older than 4.8
__builtin_bswap16 is available in all gcc architectures only since
version 4.8. Older gcc versions fail to build:

imx_sdp.o: In function `perform_dcd':
.../imx_sdp.c:1138: undefined reference to `__builtin_bswap16'
imx_sdp.o: In function `write_dcd_table_ivt':
.../imx_sdp.c:457: undefined reference to `__builtin_bswap16'
imx_sdp.o: In function `write_dcd':
.../imx_sdp.c:410: undefined reference to `__builtin_bswap16'
imx_sdp.o: In function `init_header':
.../imx_sdp.c:1075: undefined reference to `__builtin_bswap16'

Use a local implementation instead. The implementation suggested by
Arnout Vandecappelle on the Buildroot mailing list.

Signed-off-by: Baruch Siach <baruch@tkos.co.il>